#!/usr/bin/env perl
use strict;
use warnings;
use Cwd qw(abs_path);
use File::Basename qw(dirname);

my $dir = dirname abs_path $0;

if ($^O eq 'MSWin32') {
	system "plackup -I $dir/mojo/lib -I $dir/extlib/lib/perl5 @ARGV $dir/script/gitprep";
} else {
	$ENV{PERL5LIB}="$dir/mojo/lib:$dir/extlib/lib/perl5";
	system "$^X $dir/mojo/script/hypnotoad @ARGV $dir/script/gitprep";
}


