#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../extlib/lib/perl5";
use Mojo::URL;
use Gitprep;
use Gitprep::Repository;

# Retrieve our parameters
my ($user_id, $project_id, $is_wiki) =
  @ENV{'GITPREP_USER', 'GITPREP_PROJECT', 'GITPREP_IS_WIKI'};

die "Gitprep parameters unset" unless $user_id && $project_id;
exit if $is_wiki;

my $app = Mojo::Server->new->load_app("$FindBin::Bin/gitprep");
my $git = $app->git;
my $dbi = $app->dbi;

my $rep_info = Gitprep::Repository->new($user_id, $project_id);
my $default_branch = $git->current_branch($rep_info);
my $project = $dbi->model('project')->select(
  where => {'user.id' => $user_id, 'project.id' => $project_id}
)->one;

my $site_url = $app->{site_url};

while (<>) {
  chomp;
  die "Invalid update data" unless $_ =~
    m#^([0-9a-f]{40})\s([0-9a-f]{40})\s(refs/(tags|heads|remotes)/(\S+))$#i;
  my ($old, $new, $ref, $kind, $name) = ($1, $2, $3, $4, $5);
  $old =~ s/0{40}//;
  $new =~ s/0{40}//;

  if ($site_url && $kind eq 'heads' && !$old) {
    if ($project->{original_project} || $name ne $default_branch) {
      my $url = Mojo::URL->new("$user_id/$project_id/pull/new/$name");
      $url = $url->to_abs($site_url);
      print "\nCreate a pull request for '$name' on Gitprep by visiting:\n";
      print "     $url\n\n";
    }
  }
}

exit 0;
